# Generated by Django 5.2.1 on 2025-05-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_user_groups_user_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="student_class",
            field=models.CharField(
                blank=True,
                choices=[("4", "4. Sınıf"), ("5", "5. Sınıf")],
                max_length=1,
                null=True,
            ),
        ),
    ]
