# Generated by Django 5.2.1 on 2025-05-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_user_student_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "Bu e-posta adresi zaten kullanılıyor"},
                max_length=254,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="student_class",
            field=models.CharField(
                choices=[("4", "4. Sınıf"), ("5", "5. Sınıf")],
                default=4,
                error_messages={
                    "blank": "Sınıf seçimi zorunludur",
                    "invalid_choice": "Geçerli bir sınıf seçiniz (4. veya 5. sınıf)",
                },
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="student_number",
            field=models.CharField(
                error_messages={"unique": "Bu öğrenci numarası zaten kullanılıyor"},
                max_length=12,
                unique=True,
            ),
        ),
    ]
