# Generated by Django 5.2.1 on 2025-05-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_user_email_alter_user_student_class_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                fields=("unit", "date", "time_slot"),
                name="unique_reservation",
                violation_error_message="Bu ünite seçtiğiniz tarih ve saat için dolu.",
            ),
        ),
    ]
