# Generated by Django 5.2.1 on 2025-05-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_reservation_unique_reservation"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reservation",
            name="unique_reservation",
        ),
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together=set(),
        ),
    ]
