# Generated by Django 5.2 on 2025-05-18 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_test_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Pazartesi'), ('tue', 'Salı'), ('wed', 'Çarşamba'), ('thu', 'Perşembe'), ('fri', 'Cuma')], max_length=3)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day', 'teacher'],
                'unique_together': {('teacher', 'day')},
            },
        ),
        migrations.DeleteModel(
            name='ShiftList',
        ),
    ]
