# Generated by Django 5.2 on 2025-05-18 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_dutyschedule_delete_shiftlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dutyschedule',
            options={},
        ),
        migrations.RenameField(
            model_name='dutyschedule',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='dutyschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dutyschedule',
            name='friday',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dutyschedule',
            name='monday',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dutyschedule',
            name='thursday',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dutyschedule',
            name='tuesday',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dutyschedule',
            name='wednesday',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dutyschedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='dutyschedule',
            name='day',
        ),
    ]
