# Generated by Django 5.2.1 on 2025-05-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_delete_old_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="recipient_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="sender_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
