# Generated by Django 5.2.1 on 2025-05-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_usermessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dutyschedule",
            name="friday",
        ),
        migrations.RemoveField(
            model_name="dutyschedule",
            name="monday",
        ),
        migrations.RemoveField(
            model_name="dutyschedule",
            name="thursday",
        ),
        migrations.RemoveField(
            model_name="dutyschedule",
            name="tuesday",
        ),
        migrations.RemoveField(
            model_name="dutyschedule",
            name="wednesday",
        ),
        migrations.AddField(
            model_name="dutyschedule",
            name="date",
            field=models.DateField(default="2025-05-25", unique=True),
            preserve_default=False,
        ),
    ]
