# Generated by Django 5.2 on 2025-05-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_active_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.AlterField(
            model_name='user',
            name='student_class',
            field=models.IntegerField(blank=True, choices=[('4', '4. Sınıf'), ('5', '5. Sınıf')], max_length=1, null=True),
        ),
    ]
